### ISSUE TITLE
Blacklist certain language during inference

### ISSUE THREAD

**Issue by theblackcat102** [currentsapi/fastlangid#1]
Under some circumstance some language can be ignored from the final predictions, a parameters should be provided to ignore them

**Comment by guohan950106** [comment]
请问粤语相关的语料有找到吗

**Comment by theblackcat102** [comment]
@guohan950106  沒有耶，之前詢問過一些提供過粵語語料的實驗室沒有任何回覆。最接近的應該是 common voice 的粵語的文字
